`Notification` validation
CIRCULARKA/notificator pull request #10
Opened 2024-09-03 04:36 UTC by 4view

2024-09-21 18:08 UTC, CIRCULARKA commented on src/Notificator.Infrastructure/Validation/NotificationValidationService.cs
> +
Два лишних пробела? Ты сумасшедший

2024-09-21 18:13 UTC, CIRCULARKA requested changes

2024-09-21 18:13 UTC, CIRCULARKA commented on src/Notificator.Infrastructure/Validation/NotificationValidationService.cs
> +            throw new InvalidOperationException("Notification Text must not be emtpy");
"Notification's text must not be empty"

2024-09-21 18:13 UTC, CIRCULARKA commented on src/Notificator.Infrastructure/Validation/NotificationValidationService.cs
> +            throw new InvalidOperationException("Notification Header must not be empty");
"Notification's header must not be empty"

2024-09-21 18:13 UTC, CIRCULARKA commented on src/Notificator.Infrastructure/Validation/NotificationValidationService.cs
> +            throw new InvalidOperationException("Notification StartTime must be greater then current time");
"Notification's start time must be greater than the current time"

2024-09-21 18:13 UTC, CIRCULARKA commented on src/Notificator.Infrastructure/Validation/NotificationValidationService.cs
> +            throw new InvalidOperationException("Notificator MaxAmount can`t be less then 0");
"Max amount of notifications must be greater than zero"

2024-09-21 18:13 UTC, CIRCULARKA commented on src/Notificator.Infrastructure/Validation/NotificationValidationService.cs
> +            throw new InvalidOperationException("Notificator Interval could be empty or Interval value must be greater then MinInterval");
Кто такой этот ваш нотификатор. $"Notification's interval must not be less than the minimal interval of {_settings.MinInterval}"

2024-09-21 18:13 UTC, CIRCULARKA commented on src/Notificator.Infrastructure/Validation/NotificationValidationService.cs
> +            + "and difference between StartTime and EndTime shouldn't be less then MinInterval");
Слишком сложное, большое условие. Нужно разбить его на три последовательных проверки

2024-09-23 08:25 UTC, 4view commented on src/Notificator.Infrastructure/Validation/NotificationValidationService.cs
> +            throw new InvalidOperationException("Notification Header must not be empty");
@CIRCULARKA Fixed https://github.com/CIRCULARKA/notificator/pull/10/commits/03be5ba7c13d4119bb23f27620ce125dedfb3bd1

2024-09-23 08:25 UTC, 4view commented on src/Notificator.Infrastructure/Validation/NotificationValidationService.cs
> +            throw new InvalidOperationException("Notification StartTime must be greater then current time");
@CIRCULARKA Fixed https://github.com/CIRCULARKA/notificator/commit/03be5ba7c13d4119bb23f27620ce125dedfb3bd1

2024-09-23 08:26 UTC, 4view commented on src/Notificator.Infrastructure/Validation/NotificationValidationService.cs
> +            throw new InvalidOperationException("Notificator MaxAmount can`t be less then 0");
@CIRCULARKA Fixed https://github.com/CIRCULARKA/notificator/commit/03be5ba7c13d4119bb23f27620ce125dedfb3bd1

2024-09-23 08:26 UTC, 4view commented on src/Notificator.Infrastructure/Validation/NotificationValidationService.cs
> +            throw new InvalidOperationException("Notificator Interval could be empty or Interval value must be greater then MinInterval");
@CIRCULARKA Fixed https://github.com/CIRCULARKA/notificator/commit/03be5ba7c13d4119bb23f27620ce125dedfb3bd1

2024-09-23 08:26 UTC, 4view commented on src/Notificator.Infrastructure/Validation/NotificationValidationService.cs
> +            + "and difference between StartTime and EndTime shouldn't be less then MinInterval");
@CIRCULARKA Fixed https://github.com/CIRCULARKA/notificator/commit/03be5ba7c13d4119bb23f27620ce125dedfb3bd1

2024-10-31 11:01 UTC, 4view commented on src/Notificator.Infrastructure/Validation/NotificationValidationService.cs
> +        if (notificationDto.DaysOfTheWeek.Distinct().Count() != notificationDto.DaysOfTheWeek.Count)
@CIRCULARKA fixed  https://github.com/CIRCULARKA/notificator/pull/10/commits/d4fbb6d36223e7956e043cd857c27139607929c7

2024-10-31 11:03 UTC, CIRCULARKA approved these changes

2024-10-31 11:03 UTC, merged