Создание модели уведомления
CIRCULARKA/notificator pull request #5
Opened 2024-06-25 09:46 UTC by 4view

2024-07-08 18:30 UTC, CIRCULARKA commented on src/Notificator.Core/Notificator.Core.csproj
> -    <Nullable>enable</Nullable>
Надо вернуть опцию обратно. Будем с nullable работать

2024-07-09 08:13 UTC, 4view commented on src/Notificator.Tests/Notificator.Tests.csproj
> -    <Nullable>enable</Nullable>
@CIRCULARKA Done [Add nullable](https://github.com/CIRCULARKA/notificator/pull/5/commits/69833fff5ceb06e42a186c78cd007cc3490bce5b)

2024-07-09 08:15 UTC, 4view commented on src/Notificator.Tests/Notificator.Tests.csproj
> -    <Nullable>enable</Nullable>
@CIRCULARKA Done https://github.com/CIRCULARKA/notificator/pull/5/commits/a4608ff76e0e3f0037d6f4f8523cac89e1d91ed5

2024-07-09 08:16 UTC, 4view commented on src/Notificator.Infrastructure/Notificator.Infrastructure.csproj
> -    <Nullable>enable</Nullable>
@CIRCULARKA Done https://github.com/CIRCULARKA/notificator/pull/5/commits/a4608ff76e0e3f0037d6f4f8523cac89e1d91ed5

2024-07-09 11:21 UTC, CIRCULARKA requested changes

2024-07-09 11:21 UTC, CIRCULARKA commented on src/Notificator.Infrastructure/Notificator.Infrastructure.csproj
Удали пустую строку эту

2024-07-09 11:26 UTC, 4view commented on src/Notificator.Infrastructure/Notificator.Infrastructure.csproj
@CIRCULARKA Fixed https://github.com/CIRCULARKA/notificator/pull/5/commits/08a8f9994210d4b9b60c0f9994e36a5819069dc6

2024-07-09 11:28 UTC, CIRCULARKA submitted a review, later dismissed

2024-07-09 11:30 UTC, CIRCULARKA approved these changes

2024-07-09 18:08 UTC, merged